// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/theseonpb/theseon.proto

package theseonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Theseon_Put_FullMethodName              = "/theseonpb.Theseon/Put"
	Theseon_Get_FullMethodName              = "/theseonpb.Theseon/Get"
	Theseon_Delete_FullMethodName           = "/theseonpb.Theseon/Delete"
	Theseon_Scan_FullMethodName             = "/theseonpb.Theseon/Scan"
	Theseon_BatchWrite_FullMethodName       = "/theseonpb.Theseon/BatchWrite"
	Theseon_CreateCollection_FullMethodName = "/theseonpb.Theseon/CreateCollection"
	Theseon_VectorPut_FullMethodName        = "/theseonpb.Theseon/VectorPut"
	Theseon_VectorDelete_FullMethodName     = "/theseonpb.Theseon/VectorDelete"
	Theseon_VectorSearch_FullMethodName     = "/theseonpb.Theseon/VectorSearch"
)

// TheseonClient is the client API for Theseon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TheseonClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error)
	BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error)
	// Vector operations
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	VectorPut(ctx context.Context, in *VectorPutRequest, opts ...grpc.CallOption) (*VectorPutResponse, error)
	VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*VectorDeleteResponse, error)
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
}

type theseonClient struct {
	cc grpc.ClientConnInterface
}

func NewTheseonClient(cc grpc.ClientConnInterface) TheseonClient {
	return &theseonClient{cc}
}

func (c *theseonClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, Theseon_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Theseon_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Theseon_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Theseon_ServiceDesc.Streams[0], Theseon_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Theseon_ScanClient = grpc.ServerStreamingClient[ScanResponse]

func (c *theseonClient) BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteResponse)
	err := c.cc.Invoke(ctx, Theseon_BatchWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, Theseon_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) VectorPut(ctx context.Context, in *VectorPutRequest, opts ...grpc.CallOption) (*VectorPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorPutResponse)
	err := c.cc.Invoke(ctx, Theseon_VectorPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*VectorDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorDeleteResponse)
	err := c.cc.Invoke(ctx, Theseon_VectorDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theseonClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, Theseon_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheseonServer is the server API for Theseon service.
// All implementations must embed UnimplementedTheseonServer
// for forward compatibility.
type TheseonServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error
	BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error)
	// Vector operations
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	VectorPut(context.Context, *VectorPutRequest) (*VectorPutResponse, error)
	VectorDelete(context.Context, *VectorDeleteRequest) (*VectorDeleteResponse, error)
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	mustEmbedUnimplementedTheseonServer()
}

// UnimplementedTheseonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTheseonServer struct{}

func (UnimplementedTheseonServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTheseonServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTheseonServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTheseonServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedTheseonServer) BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchWrite not implemented")
}
func (UnimplementedTheseonServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedTheseonServer) VectorPut(context.Context, *VectorPutRequest) (*VectorPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorPut not implemented")
}
func (UnimplementedTheseonServer) VectorDelete(context.Context, *VectorDeleteRequest) (*VectorDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDelete not implemented")
}
func (UnimplementedTheseonServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedTheseonServer) mustEmbedUnimplementedTheseonServer() {}
func (UnimplementedTheseonServer) testEmbeddedByValue()                 {}

// UnsafeTheseonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TheseonServer will
// result in compilation errors.
type UnsafeTheseonServer interface {
	mustEmbedUnimplementedTheseonServer()
}

func RegisterTheseonServer(s grpc.ServiceRegistrar, srv TheseonServer) {
	// If the following call panics, it indicates UnimplementedTheseonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Theseon_ServiceDesc, srv)
}

func _Theseon_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TheseonServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Theseon_ScanServer = grpc.ServerStreamingServer[ScanResponse]

func _Theseon_BatchWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).BatchWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_BatchWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).BatchWrite(ctx, req.(*BatchWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_VectorPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).VectorPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_VectorPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).VectorPut(ctx, req.(*VectorPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_VectorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).VectorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_VectorDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).VectorDelete(ctx, req.(*VectorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Theseon_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheseonServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Theseon_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheseonServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Theseon_ServiceDesc is the grpc.ServiceDesc for Theseon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Theseon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theseonpb.Theseon",
	HandlerType: (*TheseonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Theseon_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Theseon_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Theseon_Delete_Handler,
		},
		{
			MethodName: "BatchWrite",
			Handler:    _Theseon_BatchWrite_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _Theseon_CreateCollection_Handler,
		},
		{
			MethodName: "VectorPut",
			Handler:    _Theseon_VectorPut_Handler,
		},
		{
			MethodName: "VectorDelete",
			Handler:    _Theseon_VectorDelete_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _Theseon_VectorSearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _Theseon_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/theseonpb/theseon.proto",
}

const (
	InternalService_Ping_FullMethodName                  = "/theseonpb.InternalService/Ping"
	InternalService_PingReq_FullMethodName               = "/theseonpb.InternalService/PingReq"
	InternalService_GossipSync_FullMethodName            = "/theseonpb.InternalService/GossipSync"
	InternalService_ReplicateWrite_FullMethodName        = "/theseonpb.InternalService/ReplicateWrite"
	InternalService_ReplicateWriteBatch_FullMethodName   = "/theseonpb.InternalService/ReplicateWriteBatch"
	InternalService_ReplicateRead_FullMethodName         = "/theseonpb.InternalService/ReplicateRead"
	InternalService_ReplicateVectorWrite_FullMethodName  = "/theseonpb.InternalService/ReplicateVectorWrite"
	InternalService_ReplicateVectorDelete_FullMethodName = "/theseonpb.InternalService/ReplicateVectorDelete"
	InternalService_ReplicateVectorSearch_FullMethodName = "/theseonpb.InternalService/ReplicateVectorSearch"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServiceClient interface {
	// SWIM protocol RPCs
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	PingReq(ctx context.Context, in *PingReqRequest, opts ...grpc.CallOption) (*PingReqResponse, error)
	GossipSync(ctx context.Context, in *GossipSyncRequest, opts ...grpc.CallOption) (*GossipSyncResponse, error)
	// Data-plane replication RPCs
	ReplicateWrite(ctx context.Context, in *ReplicateWriteRequest, opts ...grpc.CallOption) (*ReplicateWriteResponse, error)
	ReplicateWriteBatch(ctx context.Context, in *ReplicateWriteBatchRequest, opts ...grpc.CallOption) (*ReplicateWriteBatchResponse, error)
	ReplicateRead(ctx context.Context, in *ReplicateReadRequest, opts ...grpc.CallOption) (*ReplicateReadResponse, error)
	// Vector replication RPCs
	ReplicateVectorWrite(ctx context.Context, in *ReplicateVectorWriteRequest, opts ...grpc.CallOption) (*ReplicateVectorWriteResponse, error)
	ReplicateVectorDelete(ctx context.Context, in *ReplicateVectorDeleteRequest, opts ...grpc.CallOption) (*ReplicateVectorDeleteResponse, error)
	ReplicateVectorSearch(ctx context.Context, in *ReplicateVectorSearchRequest, opts ...grpc.CallOption) (*ReplicateVectorSearchResponse, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, InternalService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) PingReq(ctx context.Context, in *PingReqRequest, opts ...grpc.CallOption) (*PingReqResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReqResponse)
	err := c.cc.Invoke(ctx, InternalService_PingReq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GossipSync(ctx context.Context, in *GossipSyncRequest, opts ...grpc.CallOption) (*GossipSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipSyncResponse)
	err := c.cc.Invoke(ctx, InternalService_GossipSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateWrite(ctx context.Context, in *ReplicateWriteRequest, opts ...grpc.CallOption) (*ReplicateWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateWriteResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateWriteBatch(ctx context.Context, in *ReplicateWriteBatchRequest, opts ...grpc.CallOption) (*ReplicateWriteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateWriteBatchResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateWriteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateRead(ctx context.Context, in *ReplicateReadRequest, opts ...grpc.CallOption) (*ReplicateReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateReadResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateVectorWrite(ctx context.Context, in *ReplicateVectorWriteRequest, opts ...grpc.CallOption) (*ReplicateVectorWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateVectorWriteResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateVectorWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateVectorDelete(ctx context.Context, in *ReplicateVectorDeleteRequest, opts ...grpc.CallOption) (*ReplicateVectorDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateVectorDeleteResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateVectorDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateVectorSearch(ctx context.Context, in *ReplicateVectorSearchRequest, opts ...grpc.CallOption) (*ReplicateVectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateVectorSearchResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateVectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
type InternalServiceServer interface {
	// SWIM protocol RPCs
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	PingReq(context.Context, *PingReqRequest) (*PingReqResponse, error)
	GossipSync(context.Context, *GossipSyncRequest) (*GossipSyncResponse, error)
	// Data-plane replication RPCs
	ReplicateWrite(context.Context, *ReplicateWriteRequest) (*ReplicateWriteResponse, error)
	ReplicateWriteBatch(context.Context, *ReplicateWriteBatchRequest) (*ReplicateWriteBatchResponse, error)
	ReplicateRead(context.Context, *ReplicateReadRequest) (*ReplicateReadResponse, error)
	// Vector replication RPCs
	ReplicateVectorWrite(context.Context, *ReplicateVectorWriteRequest) (*ReplicateVectorWriteResponse, error)
	ReplicateVectorDelete(context.Context, *ReplicateVectorDeleteRequest) (*ReplicateVectorDeleteResponse, error)
	ReplicateVectorSearch(context.Context, *ReplicateVectorSearchRequest) (*ReplicateVectorSearchResponse, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedInternalServiceServer) PingReq(context.Context, *PingReqRequest) (*PingReqResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingReq not implemented")
}
func (UnimplementedInternalServiceServer) GossipSync(context.Context, *GossipSyncRequest) (*GossipSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GossipSync not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateWrite(context.Context, *ReplicateWriteRequest) (*ReplicateWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateWrite not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateWriteBatch(context.Context, *ReplicateWriteBatchRequest) (*ReplicateWriteBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateWriteBatch not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateRead(context.Context, *ReplicateReadRequest) (*ReplicateReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateRead not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateVectorWrite(context.Context, *ReplicateVectorWriteRequest) (*ReplicateVectorWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateVectorWrite not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateVectorDelete(context.Context, *ReplicateVectorDeleteRequest) (*ReplicateVectorDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateVectorDelete not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateVectorSearch(context.Context, *ReplicateVectorSearchRequest) (*ReplicateVectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateVectorSearch not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_PingReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).PingReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_PingReq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).PingReq(ctx, req.(*PingReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GossipSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GossipSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GossipSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GossipSync(ctx, req.(*GossipSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateWrite(ctx, req.(*ReplicateWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateWriteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateWriteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateWriteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateWriteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateWriteBatch(ctx, req.(*ReplicateWriteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateRead(ctx, req.(*ReplicateReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateVectorWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateVectorWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateVectorWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateVectorWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateVectorWrite(ctx, req.(*ReplicateVectorWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateVectorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateVectorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateVectorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateVectorDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateVectorDelete(ctx, req.(*ReplicateVectorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateVectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateVectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateVectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateVectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateVectorSearch(ctx, req.(*ReplicateVectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theseonpb.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _InternalService_Ping_Handler,
		},
		{
			MethodName: "PingReq",
			Handler:    _InternalService_PingReq_Handler,
		},
		{
			MethodName: "GossipSync",
			Handler:    _InternalService_GossipSync_Handler,
		},
		{
			MethodName: "ReplicateWrite",
			Handler:    _InternalService_ReplicateWrite_Handler,
		},
		{
			MethodName: "ReplicateWriteBatch",
			Handler:    _InternalService_ReplicateWriteBatch_Handler,
		},
		{
			MethodName: "ReplicateRead",
			Handler:    _InternalService_ReplicateRead_Handler,
		},
		{
			MethodName: "ReplicateVectorWrite",
			Handler:    _InternalService_ReplicateVectorWrite_Handler,
		},
		{
			MethodName: "ReplicateVectorDelete",
			Handler:    _InternalService_ReplicateVectorDelete_Handler,
		},
		{
			MethodName: "ReplicateVectorSearch",
			Handler:    _InternalService_ReplicateVectorSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/theseonpb/theseon.proto",
}

const (
	AdminService_GetNodeInfo_FullMethodName      = "/theseonpb.AdminService/GetNodeInfo"
	AdminService_GetClusterStatus_FullMethodName = "/theseonpb.AdminService/GetClusterStatus"
	AdminService_JoinRing_FullMethodName         = "/theseonpb.AdminService/JoinRing"
	AdminService_ActivateNode_FullMethodName     = "/theseonpb.AdminService/ActivateNode"
	AdminService_RemoveNode_FullMethodName       = "/theseonpb.AdminService/RemoveNode"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error)
	ActivateNode(ctx context.Context, in *ActivateNodeRequest, opts ...grpc.CallOption) (*ActivateNodeResponse, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) JoinRing(ctx context.Context, in *JoinRingRequest, opts ...grpc.CallOption) (*JoinRingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRingResponse)
	err := c.cc.Invoke(ctx, AdminService_JoinRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ActivateNode(ctx context.Context, in *ActivateNodeRequest, opts ...grpc.CallOption) (*ActivateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateNodeResponse)
	err := c.cc.Invoke(ctx, AdminService_ActivateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNodeResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	JoinRing(context.Context, *JoinRingRequest) (*JoinRingResponse, error)
	ActivateNode(context.Context, *ActivateNodeRequest) (*ActivateNodeResponse, error)
	RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedAdminServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedAdminServiceServer) JoinRing(context.Context, *JoinRingRequest) (*JoinRingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinRing not implemented")
}
func (UnimplementedAdminServiceServer) ActivateNode(context.Context, *ActivateNodeRequest) (*ActivateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateNode not implemented")
}
func (UnimplementedAdminServiceServer) RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_JoinRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).JoinRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_JoinRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).JoinRing(ctx, req.(*JoinRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ActivateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ActivateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ActivateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ActivateNode(ctx, req.(*ActivateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theseonpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _AdminService_GetNodeInfo_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _AdminService_GetClusterStatus_Handler,
		},
		{
			MethodName: "JoinRing",
			Handler:    _AdminService_JoinRing_Handler,
		},
		{
			MethodName: "ActivateNode",
			Handler:    _AdminService_ActivateNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _AdminService_RemoveNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/theseonpb/theseon.proto",
}
