// Code generated by command: go run main.go -out internal/simd/l2_amd64.s -stubs internal/simd/l2_amd64.go -pkg simd. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func l2SquaredAVX2(a []float32, b []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·l2SquaredAVX2(SB), NOSPLIT, $0-52
	MOVQ   a_base+0(FP), AX
	MOVQ   b_base+24(FP), CX
	MOVQ   a_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1

loop16:
	CMPQ        DX, $0x00000010
	JL          after16
	VMOVUPS     (AX), Y2
	VMOVUPS     32(AX), Y3
	VMOVUPS     (CX), Y4
	VMOVUPS     32(CX), Y5
	VSUBPS      Y4, Y2, Y2
	VSUBPS      Y5, Y3, Y3
	VFMADD231PS Y2, Y2, Y0
	VFMADD231PS Y3, Y3, Y1
	ADDQ        $0x00000040, AX
	ADDQ        $0x00000040, CX
	SUBQ        $0x00000010, DX
	JMP         loop16

after16:
	CMPQ        DX, $0x00000008
	JL          reduce
	VMOVUPS     (AX), Y2
	VMOVUPS     (CX), Y3
	VSUBPS      Y3, Y2, Y2
	VFMADD231PS Y2, Y2, Y0
	ADDQ        $0x00000020, AX
	ADDQ        $0x00000020, CX
	SUBQ        $0x00000008, DX

reduce:
	VADDPS       Y1, Y0, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VPERMILPS    $0xee, X0, X1
	VADDPS       X1, X0, X0
	VPERMILPS    $0x55, X0, X1
	VADDPS       X1, X0, X0
	TESTQ        DX, DX
	JZ           done

tail_loop:
	VMOVSS      (AX), X1
	VMOVSS      (CX), X2
	VSUBSS      X2, X1, X1
	VFMADD231SS X1, X1, X0
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	DECQ        DX
	JNZ         tail_loop

done:
	MOVSS X0, ret+48(FP)
	RET
