// Code generated by command: go run main.go -out internal/simd/l2_amd64.s -stubs internal/simd/l2_amd64.go -pkg simd. DO NOT EDIT.

//go:build amd64 && !purego

package simd

// l2SquaredAVX2 returns the squared Euclidean distance between a and b.
// It assumes len(a) == len(b) and AVX2+FMA support; the caller (dispatch.go)
// verifies hasAVX2() before wiring it in.
func l2SquaredAVX2(a []float32, b []float32) float32
